schemaVersion: 2.2.2
metadata:
  name: container-in-container
components:
  - name: tooling-container
    container:
      image: ghcr.io/cidrblock/container-in-container
      # memoryRequest: 256M
      # memoryLimit: 6Gi
      # cpuRequest: 250m
      # cpuLimit: 2000m
      args: ['tail', '-f', '/dev/null']
